# Generated by Django 4.1.4 on 2023-04-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='variants',
            field=models.ManyToManyField(blank=True, null=True, to='api.variant'),
        ),
    ]
